
// -*- C++ -*-
// $Id: Version.h 81722 2008-05-19 07:53:31Z johnnyw $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.

#define ACE_MAJOR_VERSION 5
#define ACE_MINOR_VERSION 6
#define ACE_BETA_VERSION 5
#define ACE_VERSION "5.6.5"
